name: Compile & Test

on: [push, pull_request]
jobs:
  codegen-verify:
    name: Verify code generation
    runs-on: [nonprod]
    steps:

      - name: Set up Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - uses: actions/checkout@v3

      - name: Run go generate
        run: |
          set -x
          sudo apt-get -y update && sudo apt-get -y install git
          make generate
          git diff | cat
          git status --porcelain=v1
          test $(git status --porcelain=v1 | wc -l) -eq 0
        env:
          GO111MODULE: on

  build:
    name: Run tests
    runs-on: [nonprod]
    strategy:
      matrix:
        go: [ '1.20' ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Run unit tests
        run: make test
